export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE';
export const CALCULATE_RESULT = 'CALCULATE_RESULT';
export const SET_TITLE = 'SET_TITLE';
export const SET_AMOUNT = 'SET_AMOUNT';
export const SWITCH_CURRENCIES = 'SWITCH_CURRENCIES';
export const CHANGE_CURRENCY = 'CHANGE_CURRENCY';
export const SET_RATES = 'SET_RATES';
export const SET_CURRENCIES_OPTIONS = 'SET_CURRENCIES_OPTIONS';